# Generated by Django 5.2 on 2025-05-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
    migrations.AddField(
        model_name='question',
        name='tag',
        field=models.CharField(
            choices=[
    ('daily_life', 'Daily Life'),
    ('sports', 'Sports'),
    ('hobbies', 'Hobbies'),
    ('technology', 'Technology'),
    ('education_career', 'Education and Career'),
    ('health_fitness', 'Health and Fitness'),
    ('travel', 'Travel'),
    ('entertainment', 'Entertainment'),
    ('food_cooking', 'Food and Cooking'),
    ('music_arts', 'Music and Arts'),
    ('books_literature', 'Books and Literature'),
    ('relationships', 'Relationships'),
    ('gaming', 'Gaming'),
    ('science_nature', 'Science and Nature'),
    ('other', 'Other'),
],
            default='general',
            max_length=20,
        ),
    ),
]

